#!/usr/bin/env python3
#
# Generating this in a for loop in Verilog causes Yosys to crash. Lol.

CLK = "delay_counter[24]"
CELL_DIM = 32;
WIDTH = 640 // CELL_DIM;
HEIGHT = 480 // CELL_DIM;

STARTUP = [
        (0, 0),
        (0, 1),
        (1, 0),
        (1, 1),
]

if __name__ == '__main__':
    print("// Generated by genaut.py. Do not edit.")
    print(f"always @(posedge {CLK}) begin")

    for i in range(0, WIDTH):
        for j in range(0, HEIGHT):
            count = f"""$countones({{
                  board[{HEIGHT - 1 if j == 0 else j - 1}][{WIDTH - 1 if i == 0 else i - 1}],
                  board[{HEIGHT - 1 if j == 0 else j - 1}][{i                             }],
                  board[{HEIGHT - 1 if j == 0 else j - 1}][{0 if i == WIDTH - 1 else i + 1}],
                  board[{j                              }][{WIDTH - 1 if i == 0 else i - 1}],
                  board[{j                              }][{0 if i == WIDTH - 1 else i + 1}],
                  board[{0 if j == HEIGHT - 1 else j + 1}][{WIDTH - 1 if i == 0 else i - 1}],
                  board[{0 if j == HEIGHT - 1 else j + 1}][{i                             }],
                  board[{0 if j == HEIGHT - 1 else j + 1}][{0 if i == WIDTH - 1 else i + 1}]
                }})
            """
            print(f"board[{j}][{i}] <= (board[{j}][{i}] && {count} == 2) || {count} == 3;")

    print("end")
